package GUI;

import ClasesBase.Administrador;
import ClasesBase.Usuario;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 * Interfaz gráfica de usuario para la gestión de bajas de clientes en la
 * aplicación
 * 
 * @author Marco
 */
public class BajaUsuario extends javax.swing.JFrame {

    Fachada fachada = Fachada.getInstancia();
    Administrador admin;

    /**
     * Creates new form Registro
     * @param admin
     */
    public BajaUsuario(Administrador admin) {
        this.admin = admin;
        initComponents();
        cerrarCampos();
    }

    /**
     * Marca aquellos campos que no deben ser editables como tal
     */
    private void cerrarCampos() {
        tfUsuario.setEditable(false);
        tfEmail.setEditable(false);
        tfEdad.setEditable(false);
        tfTelefono.setEditable(false);
    }

    /**
     * Comprobación de si el DNI que ha insertado el usuario está en un formato
     * adecuado.
     *
     * @param dni -> DNI a comprobar
     * @return -> true si es válido, false si no lo es
     */
    public boolean dniCorrecto(String dni) {
        boolean correcto = false;

        Pattern pattern = Pattern.compile("(\\d{1,8})([TRWAGMYFPDXBNJZSQVHLCKEtrwagmyfpdxbnjzsqvhlcke])");

        Matcher matcher = pattern.matcher(dni);

        if (matcher.matches()) {
            String letra = matcher.group(2);
            String letras = "TRWAGMYFPDXBNJZSQVHLCKE";

            int index = Integer.parseInt(matcher.group(1));
            index = index % 23;
            String reference = letras.substring(index, index + 1);

            if (reference.equalsIgnoreCase(letra)) {
                correcto = true;
            } else {
                correcto = false;
            }

        } else {
            correcto = false;
        }

        return correcto;
    }
    
    /**
     * Carga los datos del usuario en base a su DNI
     * @param usuario -> usuario sobre el que se cargan los datos
     */
    public void cargarCampos(Usuario usuario) {
        tfUsuario.setText(usuario.getNombre());
        tfEmail.setText(usuario.getMail());
        tfEdad.setText(String.valueOf(usuario.getEdad()));
        tfTelefono.setText(String.valueOf(usuario.getTelefono()));
    }

    /**
     * Método auxiliar para mostrar JOptionPane con mensajes de error
     *
     * @param texto -> texto que queremos que saque el JOptionPane
     */
    public void mostrarDialogError(String texto) {
        String mensajeError = "Error: .\n" + texto;
        JOptionPane.showMessageDialog(
                this,
                mensajeError,
                "Error en baja de usuario.",
                JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Comprueba si el DNI que recoge del input es correcto, si no lo es
     * saca un mensaje de error.
     * 
     * @param dni -> DNI que se comprueba
     * @return -> true si el DNI es correcto, false si no lo es
     */
    public boolean recuperacionCorrecta(String dni) {
        boolean correcto = true;
        if (!dniCorrecto(dni)) {
            correcto = false;
            mostrarDialogError("Introduce un DNI correcto. ");
        } else if (fachada.recuperarUsuario(dni) == null) {
            correcto = false;
            mostrarDialogError("El usuario no existe en la BBDD.");
        } else if (fachada.esAdmin(dni) && correcto) {
            correcto = false;
            mostrarDialogError("No puedes dar de baja a un administrador. ");
        }
        return correcto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lLoguin = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        lUsuario = new javax.swing.JLabel();
        bBaja = new javax.swing.JButton();
        tfEmail = new javax.swing.JTextField();
        lUsuario1 = new javax.swing.JLabel();
        tfDNI = new javax.swing.JTextField();
        lUsuario2 = new javax.swing.JLabel();
        tfEdad = new javax.swing.JTextField();
        lUsuario3 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        lUsuario4 = new javax.swing.JLabel();
        bAtras = new javax.swing.JButton();
        bCargarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca - Baja de usuario");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lLoguin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lLoguin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lLoguin.setText("Biblioteca - Baja Usuario");

        lUsuario.setText("Usuario: ");

        bBaja.setText("Dar de baja");
        bBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBajaActionPerformed(evt);
            }
        });

        lUsuario1.setText("Email: ");

        lUsuario2.setText("DNI:");

        lUsuario3.setText("Edad:");

        lUsuario4.setText("Teléfono:");

        bAtras.setText("Atrás");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        bCargarDatos.setText("Cargar datos");
        bCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lLoguin, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(lUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(bBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lLoguin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(bCargarDatos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(bBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAtras)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que gestiona el evento de pulsar el botón de baja,
     * recoge los datos de los TextField e intenta realizar la eliminación.
     * 
     * @param evt -> evento de pulsar el botón
     */
    private void bBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBajaActionPerformed
        String dni = tfDNI.getText();
        
        if("".equals(dni)) {
            JOptionPane.showMessageDialog(
                this,
                "Error al dar de baja. El campo de DNI no puede estar vacío",
                "Error al dar de baja",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        fachada.eliminarUsuario(dni);

        JOptionPane.showMessageDialog(
                this,
                "Usuario dado de baja: " + dni,
                "Usuario eliminado",
                JOptionPane.INFORMATION_MESSAGE);

        tfDNI.setText("");
        tfUsuario.setText("");
        tfEmail.setText("");
        tfEdad.setText("");
        tfTelefono.setText("");
    }//GEN-LAST:event_bBajaActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        new PanelAdmin(admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bAtrasActionPerformed

    /**
     * Método que gestiona el evento de pulsar el botón de carga de datos,
     * recoge el DNI del TextField y se lo pasa el método de cargar campos
     * 
     * @param evt -> evento de pulsar el botón
     */
    private void bCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargarDatosActionPerformed
        String dni = tfDNI.getText();

        if (recuperacionCorrecta(dni)) {
            cargarCampos((Usuario) fachada.recuperarUsuario(dni));
        }
    }//GEN-LAST:event_bCargarDatosActionPerformed

    /**
     * Evento de cierre de ventana, notifica al log del cierre de sesión del
     * usuario
     *
     * @param evt -> evento del cierre de ventana
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fachada.logInfoExterna("Cierre de sesión de administrador con DNI " + this.admin.getDni());
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bBaja;
    private javax.swing.JButton bCargarDatos;
    private javax.swing.JLabel lLoguin;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JLabel lUsuario1;
    private javax.swing.JLabel lUsuario2;
    private javax.swing.JLabel lUsuario3;
    private javax.swing.JLabel lUsuario4;
    private javax.swing.JTextField tfDNI;
    private javax.swing.JTextField tfEdad;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
