package GUI;

import ClasesBase.Usuario;

/**
 *
 * Interfaz de usuario para clientes enfocada a la comprobación de la disponibilidad
 * de portátiles en la biblioteca
 * 
 * @author Edu
 */
public class DisponibilidadPortatiles extends javax.swing.JFrame {

    private final Fachada fachada = Fachada.getInstancia();
    private final Usuario usuario;
    
    /**
     * Creates new form DisponibilidadPortatiles
     * @param usuario
     */
    public DisponibilidadPortatiles(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        rellenarEtiquetas();
    }

    /**
     * Rellena las etiquetas de disponibilidad en base a la consulta
     * que se hace a la base de datos.
     * Si no hay portátiles de un tipo, se expresa directamente.
     * Si no hay portátiles de ningún tipo, se le pide al usuario intentarlo 
     * más tarde
     */
    private void rellenarEtiquetas() {
        int numAsus, numApple;
        numAsus = fachada.consultarNumeroPortatilesAsusDisponibles();
        numApple = fachada.consultarNumeroPortatilesAppleDisponibles();
        
        if(numAsus == 0) 
            lAsus.setText("No hay portátiles Asus disponibles");
        else 
            lAsus1.setText("" + numAsus);
        
        if(numApple == 0)
            lApple.setText("No hay portátiles Apple disponibles");
        else 
            lApple1.setText("" + numApple);
        
        if(numAsus == 0 && numApple == 0)
            lResultado.setText("Inténtelo de nuevo más tarde");
        else
            lResultado.setText("Si desea tomar prestado un portátil, pídalo en la recepción.");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lAsus = new javax.swing.JLabel();
        lAsus1 = new javax.swing.JLabel();
        lApple = new javax.swing.JLabel();
        lApple1 = new javax.swing.JLabel();
        bAtras = new javax.swing.JButton();
        lResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca - Disponibilidad Portátiles");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lAsus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lAsus.setText("Número de portátiles Asus disponibles: ");

        lAsus1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lApple.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lApple.setText("Número de portátiles Apple disponibles: ");

        lApple1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        bAtras.setText("Atrás");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        lResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Disponibilidad de Portátiles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAsus, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lApple, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lAsus1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lApple1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lAsus1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAsus))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lApple)
                    .addComponent(lApple1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(lResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(bAtras)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón de atrás, crea un nuevo panel de usuario y se deshace de esta ventana
     *
     * @param evt -> evento de pulsar botón
     */
    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        new PanelUsuario(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bAtrasActionPerformed

    /**
     * Evento de cierre de ventana, notifica al log del cierre de sesión del
     * usuario
     *
     * @param evt -> evento del cierre de ventana
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fachada.logInfoExterna("Cierre de sesión de usuario con DNI " + this.usuario.getDni());
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lApple;
    private javax.swing.JLabel lApple1;
    private javax.swing.JLabel lAsus;
    private javax.swing.JLabel lAsus1;
    private javax.swing.JLabel lResultado;
    // End of variables declaration//GEN-END:variables
}
