package GUI;

import ClasesBase.Administrador;
import ClasesBase.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * Interfaz gráfica de usuario para la gestión del login de los usuarios
 * en la aplicación
 * 
 * @author marco
 */
public class Login extends javax.swing.JFrame {

    Fachada fachada = Fachada.getInstancia();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lLoguin = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        lUsuario = new javax.swing.JLabel();
        bEntrar = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca - Login");
        setMinimumSize(new java.awt.Dimension(520, 290));
        setPreferredSize(new java.awt.Dimension(520, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lLoguin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lLoguin.setText("Biblioteca - Iniciar sesión");
        getContentPane().add(lLoguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 300, 43));
        getContentPane().add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 140, -1));
        getContentPane().add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 140, -1));

        jLabel2.setText("Contraseña: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 80, 20));

        lUsuario.setText("DNI:");
        getContentPane().add(lUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 80, 20));

        bEntrar.setText("Entrar");
        bEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(bEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 240, 50));

        bAtras.setText("Atrás");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(bAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 70, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que gestiona el evento de pulsar el botón de login.
     * Recoge el input del TextField, comprueba si el usuario existe.
     * Si existe comprueba si es Administrador o Cliente e instancia un objeto
     * en función de esto. Redirige al usuario al panel de usuario/admin, en base
     * a sus privilegios de usuario.
     * 
     * @param evt -> evento de pulsar el botón
     */
    private void bEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarActionPerformed
        // Si el usuario es correcto, recupero usuario o admin.
        String dni = tfUsuario.getText();
        String password = new String(pfPassword.getPassword());
        if (fachada.hacerLogin(dni, password)) {
            if (fachada.esAdmin(tfUsuario.getText())) {
                Administrador recuperado = (Administrador) fachada.recuperarUsuario(dni);

                new PanelAdmin(recuperado).setVisible(true);
                this.dispose();

            } else {
                Usuario recuperado = (Usuario) fachada.recuperarUsuario(dni);

                new PanelUsuario(recuperado).setVisible(true);
                this.dispose();
            }

        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Los datos de inicio de sesión no son válidos.",
                    "Error en la autenticación",
                    JOptionPane.ERROR_MESSAGE);

            tfUsuario.setText("");
            pfPassword.setText("");
        }
    }//GEN-LAST:event_bEntrarActionPerformed

    /**
     * Método que gestiona la pulsación del botón de atrás.
     * Crea una interfaz de inicio y se deshace de esta.
     * 
     * @param evt -> evento de pulsar el botón
     */
    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bEntrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lLoguin;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
